// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockURLStorer creates a new instance of MockURLStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLStorer {
	mock := &MockURLStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockURLStorer is an autogenerated mock type for the URLStorer type
type MockURLStorer struct {
	mock.Mock
}

type MockURLStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLStorer) EXPECT() *MockURLStorer_Expecter {
	return &MockURLStorer_Expecter{mock: &_m.Mock}
}

// GetURL provides a mock function for the type MockURLStorer
func (_mock *MockURLStorer) GetURL(code string) (string, error) {
	ret := _mock.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(code)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(code)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLStorer_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type MockURLStorer_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
//   - code string
func (_e *MockURLStorer_Expecter) GetURL(code interface{}) *MockURLStorer_GetURL_Call {
	return &MockURLStorer_GetURL_Call{Call: _e.mock.On("GetURL", code)}
}

func (_c *MockURLStorer_GetURL_Call) Run(run func(code string)) *MockURLStorer_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockURLStorer_GetURL_Call) Return(s string, err error) *MockURLStorer_GetURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockURLStorer_GetURL_Call) RunAndReturn(run func(code string) (string, error)) *MockURLStorer_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// SaveURL provides a mock function for the type MockURLStorer
func (_mock *MockURLStorer) SaveURL(code string, value string) error {
	ret := _mock.Called(code, value)

	if len(ret) == 0 {
		panic("no return value specified for SaveURL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(code, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockURLStorer_SaveURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveURL'
type MockURLStorer_SaveURL_Call struct {
	*mock.Call
}

// SaveURL is a helper method to define mock.On call
//   - code string
//   - value string
func (_e *MockURLStorer_Expecter) SaveURL(code interface{}, value interface{}) *MockURLStorer_SaveURL_Call {
	return &MockURLStorer_SaveURL_Call{Call: _e.mock.On("SaveURL", code, value)}
}

func (_c *MockURLStorer_SaveURL_Call) Run(run func(code string, value string)) *MockURLStorer_SaveURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockURLStorer_SaveURL_Call) Return(_a0 error) *MockURLStorer_SaveURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockURLStorer_SaveURL_Call) RunAndReturn(run func(code string, value string) error) *MockURLStorer_SaveURL_Call {
	_c.Call.Return(run)
	return _c
}
